"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

'''
  _____               _            _   _                _____      _   _   _
 |  __ \             | |          | | (_)              / ____|    | | | | (_)
 | |__) | __ ___   __| |_   _  ___| |_ _  ___  _ __   | (___   ___| |_| |_ _ _ __   __ _ ___
 |  ___/ '__/ _ \ / _` | | | |/ __| __| |/ _ \| '_ \   \___ \ / _ \ __| __| | '_ \ / _` / __|
 | |   | | | (_) | (_| | |_| | (__| |_| | (_) | | | |  ____) |  __/ |_| |_| | | | | (_| \__ \
 |_|   |_|  \___/ \__,_|\__,_|\___|\__|_|\___/|_| |_| |_____/ \___|\__|\__|_|_| |_|\__, |___/
                                                                                    __/ |
                                                                                   |___/

 for local changes use "local_settings.py" please

'''

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qn^ikn8bdh5*5#0-+$!)!_l+_c85-dtiuw^xei78vx*3sklwr3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

USE_X_FORWARDED_HOST = True
ALLOWED_HOSTS = ["144.76.48.157"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth.apps.AuthConfig',
    'api.apps.ApiConfig',
    'mailer.apps.MailerConfig'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.mysql',
    'OPTIONS': {
      'charset' : 'utf8mb4'
    },
    'NAME': '',
    'USER': '',
    'PASSWORD': ''
  }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (

  'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

DEFAULT_FROM_EMAIL   = 'mailer@buzzinga.com'
